version: "2"
services:
  web:
    image: node:7.10.0
    working_dir: /app
    command: npm run dev
    volumes:
      - ./:/app
  serve:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./dist/:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
